language: java

jdk:
  - openjdk11

script:
  - ./gradlew test
  - ./gradlew test -Dtest.profile=integration --info
  - ./gradlew jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
