info.app.name: Tuscan Application
info.app.description: Faceit CS:GO Player Stats Analyzer
info.app.version: 1.0.0

faceit-matches:
  cutoff-date-timestamp: 1410282903

faceit:
  timeout:
    read: 1000
    connect: 1000
  retry:
    min-backoff: 300
    max-backoff: 600
    max-retries: 2

server:
  port: 8080
