faceit:
  url: 'https://open.faceit.com/data/v4'
  open-url: 'https://api.faceit.com'
  api-key: ${FACEIT_API_KEY}

spring:
  data:
    mongodb:
      host: ${MONGO_HOST}
      port: 27017
      username: ${MONGO_USER}
      password: ${MONGO_PASSWORD}
      authentication-database: ${DATABASE}
      database: ${DATABASE}

management:
  metrics:
    export:
      graphite:
        enabled: true
        host: graphite
        step: 5s
        port: 2004
    web:
      server:
        request:
          autotime:
            enabled: true

lambda-parser:
  endpoint: ${LAMBDA_ENDPOINT}
