faceit:
  url: 'https://open.faceit.com/data/v4'
  open-url: 'https://api.faceit.com/stats/api/v1'
  api-key: ${FACEIT_API_KEY}

spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@cluster0-shard-00-00-9mebi.mongodb.net:27017,cluster0-shard-00-01-9mebi.mongodb.net:27017,cluster0-shard-00-02-9mebi.mongodb.net:27017/${DATABASE}?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin